# Site settings
title: "Currriculum Vitae"
description: "Curriculum creado en Jekyll y hosteado gracias a GitHub Pages"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Juan Pedro Demarco"
resume_title:                   "Estudiante de Ingenieria Informatica"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "petydemarco@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "3489313316"
resume_contact_address:         "Campana, Buenos Aires, Argentina"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Hola! Soy Juan y este es mi curriculum virtual creado en una pagina estatica y manejo de Jekyll. Soy tecnico electrónico y estudio 
ingenieria informática en la UBA. Me gusta la programacion y la veo como algo fundamental para el futuro. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
#resume_section_links:           true
#resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/Pety-2002"
  #resume_twitter_url:           ""
  #resume_dribbble_url:          "https://dribbble.com/jag"
  #resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/juan-pedro-demarco-774b331b5/"
  resume_instagram_url:         "https://www.instagram.com/juuan_pety/"
  #resume_website_url:           ""
  #resume_medium_url:            ""
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
